version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: osp-server-image
    container_name: ojp-server-container
    ports:
      - 8080:8080
    volumes:
      - .:/app  
    tty: true